version: '3.8'


services:
  app:
    env_file:
      - .env.prod
    restart: always
    volumes: []


  db:
    env_file:
      - .env.prod
    restart: always


  redis:
    restart: always
    command: redis-server --loglevel warning
